
version: '3'

volumes:
    database-data: {}

services:
    django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /scripts/init_application
        container_name: django
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8000:80"
        depends_on:
            - database
    
    database:
        image: postgres
        container_name: postgres-db
        env_file:
            - .env
        volumes:
            - database-data:/var/lib/postgresql/data/
